# Generated by Django 6.0.6 on 2026-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfAPI', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('admin', 'Администратор')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('site', 'Институт информационных технологий'), ('ise', 'Институт инженерии'), ('bs', 'Высшая школа бизнеса'), ('sengi', 'Институт энергетики и машиностроения'), ('kma', 'Институт математики и кибернетики'), ('sog', 'Институт нефти и газа')], max_length=10),
        ),
    ]
