# Generated by Django 6.0.6 on 2026-06-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfAPI', '0003_alter_user_role_alter_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
    ]
